name: downscaling
channels:
  - conda-forge
  - defaults
dependencies:
  - dask==2023.4.1
  - dask-core=2023.4.1
  - h5netcdf=1.1.0
  - h5py=3.8.0
  - hdf5=1.14.0
  - ipython=8.12.0
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - netcdf4=1.6.3
  - pandas==2.0.0
  - pip=23.0.1
  - pyproj=3.5.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pyyaml=6.0
  - rasterio=1.3.6
  - rioxarray=0.14.1
  - scikit-learn=1.2.2
  - setuptools=66.0.0
  - xarray==2023.4.1
  - yaml=0.2.5
  - pip:
      - cdsapi==0.6.1
      - munch==2.5.0
      - numpy==1.24.2
      - pvlib==0.9.5
      - requests==2.30.0
      - scipy==1.10.1
      - seaborn==0.12.2
      - topocalc==0.5.0
      - TopoPyScale==0.2.2
      - tqdm==4.65.0
